### ISSUE TITLE
Thermostats

### ISSUE THREAD

**Issue by dorr14** [jaroschek/home-assistant-myuplink#121]
Hi Guys, I have recently migrated over to the myUplink service for my NIBE heatpump as they are decommissioning the old uplink in August. I was wondering if anyone had any success in adding thermostats to the new myuplink API for Nibe? In the old Nibe Uplink you were able to add the thermostats via the config YAML however I can't see how to do the same for the new service.

**Comment by woopstar** [comment]
Do you have some examples of thermostats ?

**Comment by dorr14** [comment]
The thermostat are in HA via the taro integration.

**Comment by Dizzybacon** [comment]
I'm in the same position as OP. Forced to move from uplink to myuplink and I can't find a way to set up the thermostat. 
This is an example of how the thermostat was configured in the uplink world.

```
nibe:
  systems:
    # System identifier to add extra entities too
    - system: 176004
      # Optional smart thermostats.
      thermostats:
        # Key in dict is external identifer in nibe uplink, it should
        # be an unique integer for this thermostat
        1:
          # Required friendly name of thermostat
          name: 'Thermostat'

          # Optional name of a home assistant entity representing current temperature
          current_temperature: sensor.sensor_temperature

          # Optional name of a home assistant entity representing valve position of
          # a thermostat. At the moment it's use case is unknown.
          # valve_position: input_number.valve

          # List of systems that this thermostat is affecting. This is
          # this is the sub climate system/area index (System 1, System 2, ..)
          # that the pump is controlling.
          systems: 1

```

It uses the configured sensor to tell the heat pump the current room temperature and gives an input where you can set the desired temperature. Looking at the values in myuplink I can find the desired temperature, but not the current temperature so I don't know what the heat pump thinks the room temperature is or where it gets that value from.

**Comment by IngmarStein** [comment]
I've asked their support team about the fate of the "smart thermostat" feature - I worry it might have been lost in the Nibe Uplink -> MyUplink transition.

**Comment by Linqman** [comment]
I have also asked Nibe about smart thermostats, and today I received a reply that the feature is in development and will be launched later this year.

**Comment by IngmarStein** [comment]
Thanks for the update! My inquiry was acknowledged but is still in progress.

**Comment by kimsvane** [comment]
Hi

Sorry for my maybe stupid question, but was it really possible to use an external temperature data and feed it to the API for the heatpump to measure and give the most correct output ? 
It sounds like exactly what i need. 

So the the reference above, you just provided a tempature to current_temperature: sensor.sensor_temperature and the heatpump recieved this, and set the heat generation accordingly ?

**Comment by dorr14** [comment]
Yes, that is exactly what it used to do. The internel temp sensor, coupled
with the weather compensation to determine the target internal flow. Sadly
when they moved to the new uplink they removed this capability from the
API.

**Comment by Linqman** [comment]
Yep, and you could create several smart thermostats, I had one using a sensor in my living room and another for my shower.

**Comment by kimsvane** [comment]
Damn, I would really like this to be implemented again. 
It would solve our biggest problem with the heatpump, since currently our living room has many windows, and therefore it get's really hot during sunny days, so hot we have to open windows, and ideally that should also result in the heatpump not being used during those hours. except for water.

**Comment by oskarannas** [comment]
Anyone heard anything new on this? The year is almost over :)

**Comment by IngmarStein** [comment]
Last I heard was "it is being tested right now".

**Comment by oskarannas** [comment]
> Last I heard was "it is being tested right now".

Great, thanks!

**Comment by enoch85** [comment]
Does anyone have any news on this? Since we only have one "Nibe-branded" thermostat and like 10 others for indoor temp, it's not calculating the correct temp and heats the house even when not needed.

Like today, temp is set to 20.5° and the average temp from all our external sensors are 22.7°, still the pump is at 95 Hz and producing heat since it thinks that the indoor temp is 20.2°.

**Comment by RubenWaterman** [comment]
I requested an update from Nibe today and only got this reply :(

> Hi,
> The functionality with your kind of thermostat has indeed not yet been implemented in myUplink. The developers are currently working on a new feature that will enable this, and it is expected to be released later this year. Unfortunately, we do not have a more precise timeline at this moment.

**Comment by dorr14** [comment]
> I got a different response today: the feature seems to have been implemented with firmware 9714R2 and the settings are called `indoorTempOverride` and `indoorSpHeatOverride`.

That is good news, any idea how to write it into the YAML config?

**Comment by IngmarStein** [comment]
I was just forwarding the news in verbatim. I haven't found any settings matching these categories in the API responses for my F-1155, unfortunately. I've sent a follow-up inquiry and asked for the concrete parameter IDs.

**Comment by Jensner89** [comment]
> I was on the phone with Nibe this week. Apparently, the were surprised about complaints from people who used the Smart Thermostats feature in the past. They thought it was unused and didn‘t need to be ported to MyUplink. Details about the missing wndpoint now reached the right product manager in Sweden.

Thank you for this update. Hopefully, they will integrate the endpoint again.
Loos like they are having an „efficient“ monitoring on their API usage 😅

**Comment by SchinderhannesX** [comment]
Sorry for being a bit overwhelmed, but maybe I can actually add some useful information here.
For the first (main) heating circuit that the Nibe supplies, you can actually “fake” a thermometer on BT50 so you can inject the indoor temperature—potentially as a temperature synthesized from several readings in the house. This is what I’ve been doing successfully for 48 hours now. It’s a lot more reliable than a THS 10 relayed over a single RPP10, which only gives one reading from one room (with all the impacts of open windows, etc.). By averaging a couple of thermometers throughout the house and ignoring the ones in rooms with open windows, you can get a much better result.
Works great, but it’s neither in the Nibe Modbus integration nor in myUplink. It’s “straight Modbus” to the SMO S40 in my case, configured in YAML—sorry for being a bit German here. 😅
# ============================================================
# Nibe SMO S40 – BT50 Raumtemperatursteuerung via Modbus TCP
# Voraussetzung: SMO S40 Firmware ≥ 4.2.4, BT50 auf "steuerbar" gesetzt
# Verbindung: tcp://192.168.xxx.yyy:502
# ============================================================
modbus:
  - name: nibe_bt50
    type: tcp
    host: 192.168.xxx.yyy
    port: 502
    sensors:
      # ------------------------------------------------------
      # BT50 Aktivierung (Register 5986) – 0 = deaktiviert, 1 = aktiviert
      # ------------------------------------------------------
      - name: BT50 Aktivierung
        unique_id: nibe_bt50_enable
        address: 5986
        slave: 1
        input_type: holding
        data_type: int16
        scan_interval: 30

      # ------------------------------------------------------
      # BT50 Temperaturwert (Register 5987) – Wert in 0.1 °C-Schritten
      # Beispiel: 217 = 21.7 °C
      # ------------------------------------------------------
      - name: BT50 Temperaturwert
        unique_id: nibe_bt50_temperature
        address: 5987
        slave: 1
        input_type: holding
        data_type: int16
        scan_interval: 30
# ============================================================
# Ende BT50 Modbus-Konfiguration
# Nach dem Speichern Home Assistant neu starten.
# ============================================================


This gives you the option to activate this feature and use it!
That solved a good half of my problem, as the important rooms to read temperature were far away from the pump.
Luckily, the second heating circuit (underfloor heating controlled by a mixer valve, always a bit cooler than the radiators) is closer to the SMO S40. Here, the other THS 10 relayed over an RPP10 works reliably. Also, this is one large open room/kitchen, so one reading is always sufficient.
Now I have two nicely working temperature readings showing up in myUplink.
With that, I get the option in myUplink to control the desired temperature.
For some reason, with the cloud, updating the values takes forever (>5 sec) in the app.
And in HA, I can display the values coming from myUplink, and they are marked as editable—but if I move the sliders, nothing happens. No change in the myUplink app, and once you leave the section in HA and come back, the old value is displayed again. Smells like a bug to me. So here I would be grateful if those new controls Ingmar wrote about would materialize in the HA myUplink integration.
On the other hand, the BT50 Modbus integration seems really fast and reliable without the cloud. I’ll probably keep using this for the temp injection. (Would love to find a way to control BT51 for the second circuit as well—if anyone is a Modbus-sniffing wizard, LOL.)

**Comment by Jensner89** [comment]
> This is what I got:
> 
> > To integrate smart thermostat control, please use the standard myUplink data point API. You can retrieve the available points through:
> > GET /v2/devices/{deviceId}/points
> > Look for the data points that belong to the following smartHomeCategories:
> > • sh-indoorTempOverride for overriding the indoor sensor
> > • sh-indoorSpHeatOverride for overriding the heating setpoint
> > • sh-indoorSpCoolOverride for overriding the cooling setpoint
> > You will find these points once for each climate system on the device. The old behavior where multiple thermostats could be registered individually is no longer supported. If you use several thermostats per climate system, the recommended approach is to calculate the average value locally and send that value to the cloud. This has the same functional effect as the previous API.
> > To apply changes, update the relevant data points using:
> > PATCH /v2/devices/{deviceId}/points
> > Finally, the valve position parameter was removed because the value was never used by the devices when connected to NIBE Uplink.

@IngmarStein Thank you so much 🙏
That was the missing puzzle tile. I did not expect that this endpoint will work, since the GET API always returned `writable:false` for all mentioned fields, but the PATCH request has modified the data and also the heatpumps display shows the right current temperature 👌

From now on, avarages temperatures from our house will be sent again to MyUplink 🙃

@SchinderhannesX - sorry, I have not conneted our NIBE via modbus, since for me there is no real need for realtime data/modification.

**Comment by Linqman** [comment]
I did it, in perhaps a quite cumbersome way :-)

I have a script like this:

```
sequence:
  - action: myuplink.set_device_parameter_value
    metadata: {}
    data:
      device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      parameter_id: "50225"
      value: "{{ '0' ~ temperature_value | string}}"
alias: Script to update indoor temperature to Nibe
description: ""
fields:
  temperature_value:
    selector:
      number:
        min: 1
        max: 100
    name: Temperature value
```

That is being called by an automation like this, that passes the indoor temperature to it:

```
alias: Transfer indoor temperature to Nibe
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
actions:
  - action: script.script_to_update_indoor_temperature_to_nibe
    metadata: {}
    data:
      temperature_value: "{{ states('sensor.vardagsrum_temperature')}}"
mode: single
```

The reason I did it like this is that this was the only way I figured out how to pass the decimal value of the thermometer as a string to the myuplink.set_device_parameter_value service. If you call the service with the temperature value like "22.5", for example, then Homeassistant types the string to a decimal, which the service does not accept.

**Comment by Jensner89** [comment]
After successful use of the API to send indoor temps, I am facing a new issue. From time to time I am getting an error „48: Connection between indoor sensor and heatpump lost“.
The error stays even after I called the endpoint with current temperatures. There is no BT-50 sensor installed in our system. The only way to continue is to manually reset the error.
I believe the error occurs when NIBE runs some update on their side and the backend is not available.

Does someone face similar errors and has some proper solution? 🙃

**Comment by Dizzybacon** [comment]
Thanks @Linqman !
That's a big help. Any reason that you split it out into a separate script?
I've had it running for a day now and it works pretty well, but sometimes it fails and I can see that the Nibe temperature value is not following my thermometer properly.

I'm trying it now with one automation and rounding it to one decimal place to see if that helps.

```
alias: Transfer indoor temperature to Nibe
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.landing_sensor_temperature
actions:
  - action: myuplink.set_device_parameter_value
    metadata: {}
    data:
      device_id: 0b746f1a70f6edd84e8820b99ea9856e
      parameter_id: "50225"
      value: >-
        {{'0' ~  states('sensor.landing_sensor_temperature') | float(0) |
        round(1) }}
mode: single
```

Looking at the history in HA of the indoor temperature value that it receives from Nibe I think the reason it doesn't update every time and doesn't follow the indoor temperature value closely is that it doesn't change if the difference is less than 0.5C.
